### ISSUE TITLE
union types

### ISSUE THREAD

**Issue by tmcgrath** [speedment/avro-mocker#1]
Any ideas on how to update code to support union types?

Here's snippet of schema I'm attempting to use

{
     "namespace":"org.apache.spot",
     "name":"event",
     "type": "record",
     "fields": [
        {"name":"event_time","type":["null","long"],"doc":"timestamp of event (UTC)", "default": null},
        {"name":"begin_time","type":["null","long"],"doc":"timestamp of event (UTC)", "default": null},
        {"name":"end_time","type":["null","long"],"doc":"timestamp of event (UTC)", "default": null},
        {"name":"event_insert_time","type":["null","long"],"doc":"timestamp of event (UTC)", "default": null},

java -jar avro-mocker.jar -schema event.avsc -result my-data.avro
How many records should be generated: 10
Exception in thread "main" java.lang.IllegalArgumentException: The avro type 'union' is currently not supported.
	at com.speedment.avromocker.Main.main(Main.java:110)

Maybe just choose based on second value?  long is this example.

**Comment by Pyknic** [comment]
I have added a `UNION` type in the master branch so it should work for you now. Basically, if one of the types in the `UNION` is `NULL`, then it will prompt for a null-probability and handle the remaining types as usual. If there are more than one type in the `UNION` except for `NULL`, then it will prompt for which type to generate for.
